export const FRESHSALES_PRODUCT_CUSTOM_FIELDS = {
  serviceCategory: "cf_service_category",
  serviceSubCategory: "cf_service_sub_category",
  universalPlatform: "cf_universal_platform",
  baseServiceName: "cf_base_service_name",
  catalogServiceId: "cf_catalog_service_id",
  status: "cf_services_status",
  flavors: "cf_flavors",
  serviceSpecificEnhancements: "cf_service_specific_enhancements",
  aui: "cf_aui",
  updatedMainMachine: "cf_updated_main_machine",
  updatedMachine2: "cf_updated_machine_2",
  updatedMachine3: "cf_updated_machine_3",
  groceryYN: "cf_grocery_y_n",
  groceryNeeds: "cf_grocery_needs",
  kitchenPrepNeededYN: "cf_kitchen_prep_needed_y_n",
  kitchenPrepItems: "cf_kitchen_prep_items",
  carryThroughYN: "cf_carry_through_y_n",
  carryThroughItems: "cf_carry_through_items",
  orderItemsFromCC: "cf_order_items_from_cc",
  ccItems: "cf_cc_items",
  strategicAttributes: "cf_strategic_attributes",
  exclusivityKeys: "cf_exclusivity_keys",
  staff: "cf_staff",
  preSupplyTier: "cf_pre_supply_tier",
  twoDayPrice: "cf_2_day",
  threeDayPrice: "cf_3_day",
  fourDayPrice: "cf_4_day",
  notes: "cf_notes",
  finalValue: "cf_final_value",
} as const;

export const FRESHSALES_REQUIRED_PRODUCT_FIELDS = [
  {
    label: "Category",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.serviceCategory,
    type: "Text or Dropdown",
  },
  {
    label: "Sub Category",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.serviceSubCategory,
    type: "Text or Dropdown",
  },
  {
    label: "Universal Platform",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.universalPlatform,
    type: "Text or Dropdown",
  },
  {
    label: "Base Service Name",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.baseServiceName,
    type: "Text or Dropdown",
  },
  {
    label: "Flavors",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.flavors,
    type: "Text Area",
  },
  {
    label: "Service-Specific Enhancements",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.serviceSpecificEnhancements,
    type: "Text Area",
  },
  {
    label: "AUI",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.aui,
    type: "Text or Dropdown",
  },
  {
    label: "Updated Main Machine",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.updatedMainMachine,
    type: "Text or Dropdown",
  },
  {
    label: "Updated Machine 2",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.updatedMachine2,
    type: "Text or Dropdown",
  },
  {
    label: "Updated Machine 3",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.updatedMachine3,
    type: "Text or Dropdown",
  },
  {
    label: "Final Value",
    apiName: FRESHSALES_PRODUCT_CUSTOM_FIELDS.finalValue,
    type: "Text Area",
  },
] as const;
